# Site settings
title: Michael Ulrich
email: michaeldulrich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first time using Netlify and Jekyll, but wow is this easy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: michaelulrich
github_username:  michaeldulrich

# Build settings
markdown: kramdown
